--create tablespace
 --  otm_data
 --  datafile
 --  'otm_data.dbf'
 --  size 50m
 --  autoextend on;

CREATE USER otm IDENTIFIED BY otmpw DEFAULT TABLESPACE otm_data QUOTA UNLIMITED ON otm_data;
GRANT CREATE SESSION TO otm;
GRANT CREATE TABLE TO otm;
GRANT CREATE TRIGGER TO otm;
GRANT CREATE SEQUENCE TO otm;

CREATE TABLE otm.volunteer (
  ratingid		NUMBER(15) NOT NULL,
  ldsid			NUMBER(25) NOT NULL,
  CONSTRAINT volunteer_pk PRIMARY KEY (ldsid)
);

CREATE TABLE otm.missionary (
  ldsid			NUMBER(25) NOT NULL,
  CONSTRAINT missionary_pk PRIMARY KEY (ldsid)
);

ALTER TABLE OTM.MISSIONARY
  ADD (FIRST_NAME               VARCHAR2(50)  DEFAULT '---'  NOT NULL,
       LAST_NAME                VARCHAR2(50)  DEFAULT '---'  NOT NULL,
       PHOTO_URL                VARCHAR2(50),
       MISSION                  VARCHAR2(100)  DEFAULT '---'  NOT NULL,
       STATUS                   NUMBER(1)  DEFAULT 0  NOT NULL,
       MISSIONARY_TYPE          VARCHAR2(50)  DEFAULT '---'  NOT NULL,
       TRAINING_LANGUAGE        VARCHAR2(20)  DEFAULT '---'  NOT NULL,
       TRAINING_END_DATE        DATE,
       PHONE_PRIMARY            VARCHAR2(20),
       PHONE_MOBILE             VARCHAR2(20),
       EMAIL                    VARCHAR2(50),
       SKYPE                    VARCHAR2(50),
       LEARNING_COACH_ID        VARCHAR2(20),
       LANGUAGE_TUTOR_ID        VARCHAR2(20),
       TRAINING_COORDINATOR_ID  VARCHAR2(20)
       );
	   
CREATE TABLE OTM.COMPANIONSHIPS (
  MID NUMBER(25)  NOT NULL,
  CID NUMBER(25)  NOT NULL,
  CONSTRAINT FK_MID
    FOREIGN KEY (MID) REFERENCES OTM.MISSIONARY(LDSID),
  CONSTRAINT FK_CID
    FOREIGN KEY (CID) REFERENCES OTM.MISSIONARY(LDSID)
);

ALTER TABLE OTM.MISSIONARY
  MODIFY PHOTO_URL VARCHAR2(200);
  
ALTER TABLE OTM.MISSIONARY
	RENAME COLUMN FIRST_NAME TO FIRSTNAME;
	
ALTER TABLE OTM.MISSIONARY
	RENAME COLUMN LAST_NAME TO LASTNAME;
	
ALTER TABLE OTM.MISSIONARY
	RENAME COLUMN PHOTO_URL TO PHOTOURL;
	
ALTER TABLE OTM.MISSIONARY
	RENAME COLUMN MISSIONARY_TYPE TO MISSIONARYTYPE;
	
ALTER TABLE OTM.MISSIONARY
	RENAME COLUMN TRAINING_LANGUAGE TO TRAININGLANGUAGE;
	
ALTER TABLE OTM.MISSIONARY
	RENAME COLUMN TRAINING_END_DATE TO TRAININGENDDATE;
	
ALTER TABLE OTM.MISSIONARY
	RENAME COLUMN PHONE_PRIMARY TO PHONEPRIMARY;
	
ALTER TABLE OTM.MISSIONARY
	RENAME COLUMN PHONE_MOBILE TO PHONEMOBILE;
	
ALTER TABLE OTM.MISSIONARY
	RENAME COLUMN LEARNING_COACH_ID TO LEARNINGCOACHID;
	
ALTER TABLE OTM.MISSIONARY
	RENAME COLUMN LANGUAGE_TUTOR_ID TO LANGUAGETUTORID;
	
ALTER TABLE OTM.MISSIONARY
	RENAME COLUMN TRAINING_COORDINATOR_ID TO TRAININGCOORDINATORID;
	
CREATE TABLE otm.tutor (
  ldsid			 varchar2(25) NOT NULL,
  firstname  varchar2(50) NOT NULL,
  lastname   varchar2(50) NOT NULL,
  photourl   varchar2(200) NOT NULL,
  learningcoach number(1)  NOT NULL,
  volunteercoordinator number(1) NOT NULL,
  zoneassignment varchar2(50) NOT NULL,
  phoneprimary            VARCHAR2(20),
  phonemobile             VARCHAR2(20),
  email varchar2(50),
  skype varchar2(50),
  hiredate       DATE,
  CONSTRAINT tutor_pk PRIMARY KEY (ldsid)
);

CREATE TABLE otm.tutorlanguages (
  tutorid varchar2(25)  NOT NULL,
  language varchar2(50)  NOT NULL,
  fluency varchar2(20)  NOT NULL,
  CONSTRAINT fk_tutorid
    FOREIGN KEY (tutorid) REFERENCES otm.tutor(LDSID)
);

ALTER TABLE missionary  
  RENAME COLUMN status to active;
  
ALTER TABLE missionary
  ADD status VARCHAR2(20 BYTE);

